name: Build and Deploy to Plesk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: node build.js
    
    - name: List build files
      run: ls -la public/
    
    - name: Commit build files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/ -f
        git diff --quiet && git diff --staged --quiet || git commit -m "Build: Update public directory [skip ci]"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main